[tool.isort]
py_version = 3
line_length = 99
profile = "google"
src_paths = ["mongorunway", "tests"]

[tool.mypy]
strict = true
allow_redefinition = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
implicit_reexport = false
show_error_codes = true

# Warnings
warn_unused_configs = true
warn_return_any = false
warn_unreachable = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.black]
line-length = 99
target-version = ["py39"]
